#Created by: PyQt5 UI code generator 5.15.4


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Input_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Input_groupBox.setGeometry(QtCore.QRect(80, 60, 441, 211))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Input_groupBox.setFont(font)
        self.Input_groupBox.setObjectName("Input_groupBox")
        self.Operation_comboBox = QtWidgets.QComboBox(self.Input_groupBox)
        self.Operation_comboBox.setGeometry(QtCore.QRect(190, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Operation_comboBox.setFont(font)
        self.Operation_comboBox.setObjectName("Operation_comboBox")
        self.Operation_comboBox.addItem("")
        self.Operation_comboBox.addItem("")
        self.Operation_comboBox.addItem("")
        self.Operation_comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.Input_groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.Input_groupBox)
        self.label_4.setGeometry(QtCore.QRect(270, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.calculate_button = QtWidgets.QPushButton(self.Input_groupBox)
        self.calculate_button.setGeometry(QtCore.QRect(170, 120, 101, 41))
        self.clear_button = QtWidgets.QPushButton(self.Input_groupBox)
        self.clear_button.setGeometry(QtCore.QRect(170, 175, 101, 25))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calculate_button.setFont(font)
        self.calculate_button.setObjectName("calculate_button")
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.Opr1_lineEdit = QtWidgets.QLineEdit(self.Input_groupBox)
        self.Opr1_lineEdit.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.Opr1_lineEdit.setObjectName("Opr1_lineEdit")
        self.Opr2_lineEdit = QtWidgets.QLineEdit(self.Input_groupBox)
        self.Opr2_lineEdit.setGeometry(QtCore.QRect(270, 70, 161, 31))
        self.Opr2_lineEdit.setObjectName("Opr2_lineEdit")
        self.WaitList_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.WaitList_groupBox.setGeometry(QtCore.QRect(80, 300, 441, 481))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.WaitList_groupBox.setFont(font)
        self.WaitList_groupBox.setObjectName("WaitList_groupBox")
        self.WaitList_tableWidget = QtWidgets.QTableWidget(self.WaitList_groupBox)
        self.WaitList_tableWidget.setGeometry(QtCore.QRect(30, 41, 381, 421))
        self.WaitList_tableWidget.setColumnCount(3)
        self.WaitList_tableWidget.setColumnWidth(2, 0)  # Hide the third column
        self.WaitList_tableWidget.setObjectName("WaitList_tableWidget")
        self.WaitList_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.WaitList_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.WaitList_tableWidget.setHorizontalHeaderItem(1, item)
        self.WaitList_tableWidget.horizontalHeader().setDefaultSectionSize(184)
        self.History_groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.History_groupBox_2.setGeometry(QtCore.QRect(600, 60, 941, 721))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.History_groupBox_2.setFont(font)
        self.History_groupBox_2.setObjectName("History_groupBox_2")
        self.History_tableWidget = QtWidgets.QTableWidget(self.History_groupBox_2)
        self.History_tableWidget.setGeometry(QtCore.QRect(10, 40, 921, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.History_tableWidget.sizePolicy().hasHeightForWidth())
        self.History_tableWidget.setSizePolicy(sizePolicy)
        self.History_tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.History_tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.History_tableWidget.setAutoFillBackground(True)
        self.History_tableWidget.setLineWidth(10)
        self.History_tableWidget.setColumnCount(5)
        self.History_tableWidget.setObjectName("History_tableWidget")
        self.History_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.History_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.History_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.History_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.History_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.History_tableWidget.setHorizontalHeaderItem(4, item)
        self.History_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.History_tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.ConnectionStatus_label = QtWidgets.QLabel(self.centralwidget)
        self.ConnectionStatus_label.setGeometry(QtCore.QRect(150, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.ConnectionStatus_label.setFont(font)
        self.ConnectionStatus_label.setText("OK")
        self.ConnectionStatus_label.setObjectName("ConnectionStatus_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1282, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "Connect status:"))
        self.Input_groupBox.setTitle(_translate("MainWindow", "Input"))
        self.Operation_comboBox.setItemText(0, _translate("MainWindow", "+"))
        self.Operation_comboBox.setItemText(1, _translate("MainWindow", "-"))
        self.Operation_comboBox.setItemText(2, _translate("MainWindow", "*"))
        self.Operation_comboBox.setItemText(3, _translate("MainWindow", "/"))
        self.label_2.setText(_translate("MainWindow", "First Operand"))
        self.label_4.setText(_translate("MainWindow", "Second Operand"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.clear_button.setText(_translate("MainWindow", "X"))
        self.WaitList_groupBox.setTitle(_translate("MainWindow", "Waiting List"))
        item = self.WaitList_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Operation"))
        item = self.WaitList_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.History_groupBox_2.setTitle(_translate("MainWindow", "History"))
        item = self.History_tableWidget.horizontalHeaderItem(0)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setText(_translate("MainWindow", "Request timestamp"))
        item = self.History_tableWidget.horizontalHeaderItem(1)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setText(_translate("MainWindow", "  Response timestamp  "))
        item = self.History_tableWidget.horizontalHeaderItem(2)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setText(_translate("MainWindow", "Operation"))
        item = self.History_tableWidget.horizontalHeaderItem(3)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setText(_translate("MainWindow", "Status"))
        item = self.History_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Result"))
        item.setTextAlignment(QtCore.Qt.AlignCenter)